version: "0.1"

services:
  trainer:
    build:
      context: .
    entrypoint: "when-changed -s -r ./spira 'poetry run python -m spira.tasks.train'"
    profiles:
      - "dev"
    image: "spira-training"
    volumes:
      - ".:/app/"
      - "/app/.venv"